import { useState, useMemo } from "react";
import { OrderActions } from "./components/OrderActions";
import { OrderStatsComponent } from "./components/OrderStats"; // Import as-is
import { OrderFiltersComponent } from "./components/OrderFilters"; // Import as-is
import { OrderCard } from "./components/OrderCard";
import OrderDetailsDialog from "./components/OrderDetailsDialog";
import {
  filterOrders,
  sortOrders,
  calculateOrderStats,
  exportCSV,
  exportPDF,
  bulkUpdateOrders,
  markAsPickedUp,
  markAsReady,
  cancelOrder,
  initialOrders,
} from ".";
import type { Order } from "./types/orders.types";

// Add missing printOrder function
const printOrder = (order: Order) => {
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(`
      <html>
        <head>
          <title>Order ${order.orderNumber}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            .header { text-align: center; margin-bottom: 30px; }
            .section { margin-bottom: 20px; }
            .label { font-weight: bold; color: #666; }
            .value { margin-bottom: 10px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Order Receipt</h1>
            <h2>${order.orderNumber}</h2>
            <p>Date: ${new Date().toLocaleDateString()}</p>
          </div>
          
          <div class="section">
            <div class="label">Customer:</div>
            <div class="value">${order.customerName}</div>
            
            <div class="label">Vendor:</div>
            <div class="value">${order.vendorName}</div>
            
            <div class="label">Pickup:</div>
            <div class="value">${order.pickupTime}</div>
            
            <div class="label">Address:</div>
            <div class="value">${order.deliveryAddress}</div>
          </div>
          
          <div class="section">
            <div class="label">Items:</div>
            <div class="value">${order.items} × ${order.quantity}</div>
            
            <div class="label">Amount:</div>
            <div class="value" style="font-size: 24px; font-weight: bold;">${order.totalAmount}</div>
          </div>
          
          <div class="section">
            <div class="label">Status:</div>
            <div class="value">${order.status}</div>
            
            <div class="label">Payment Method:</div>
            <div class="value">${order.paymentMethod}</div>
          </div>
          
          ${
            order.notes
              ? `
          <div class="section">
            <div class="label">Notes:</div>
            <div class="value">${order.notes}</div>
          </div>`
              : ""
          }
          
          <hr style="margin: 30px 0;" />
          <p style="text-align: center; color: #666;">
            Generated by Order Management System
          </p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }
};

export function OrdersView() {
  const [orders, setOrders] = useState(initialOrders);
  const [selectedOrders, setSelectedOrders] = useState<string[]>([]);
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  const [filterOptions, setFilterOptions] = useState({
    searchTerm: "",
    filterStatus: "all",
    minAmount: "",
    maxAmount: "",
    startDate: "",
    endDate: "",
    sortBy: "dateDesc",
    itemsPerPage: 5,
    currentPage: 1,
  });

  // Apply filters and sorting
  const filteredOrders = useMemo(
    () => filterOrders(orders, filterOptions),
    [orders, filterOptions],
  );

  const sortedOrders = useMemo(
    () => sortOrders(filteredOrders, filterOptions.sortBy),
    [filteredOrders, filterOptions.sortBy],
  );

  // Calculate stats
  const stats = useMemo(() => calculateOrderStats(orders), [orders]);

  // Pagination
  const totalPages = Math.ceil(
    sortedOrders.length / filterOptions.itemsPerPage,
  );
  const startIndex =
    (filterOptions.currentPage - 1) * filterOptions.itemsPerPage;
  const endIndex = startIndex + filterOptions.itemsPerPage;
  const pagedOrders = sortedOrders.slice(startIndex, endIndex);

  // Event handlers
  const handleFilterChange = (updates: Partial<typeof filterOptions>) => {
    setFilterOptions((prev) => ({ ...prev, ...updates }));
  };

  const handleBulkAction = (
    action: "complete" | "cancel" | "print" | "ready",
  ) => {
    setOrders(bulkUpdateOrders(orders, selectedOrders, action));
    setSelectedOrders([]);
  };

  const handleExportCSV = () => exportCSV(filteredOrders);
  const handleExportPDF = () => exportPDF(filteredOrders, stats);

  return (
    <div className="p-8 bg-gray-50 min-h-screen">
      <OrderActions
        onExportCSV={handleExportCSV}
        onExportPDF={handleExportPDF}
        totalOrders={sortedOrders.length}
        itemsPerPage={filterOptions.itemsPerPage}
        onItemsPerPageChange={(value) =>
          handleFilterChange({ itemsPerPage: value, currentPage: 1 })
        }
        currentPage={filterOptions.currentPage}
        totalPages={totalPages}
        onPageChange={(page) => handleFilterChange({ currentPage: page })}
      />

      {/* Use the correct component names */}
      <OrderStatsComponent stats={stats} />

      <OrderFiltersComponent
        filters={filterOptions}
        onFilterChange={handleFilterChange}
        selectedOrdersCount={selectedOrders.length}
        onBulkAction={handleBulkAction}
        onClearSelection={() => setSelectedOrders([])}
      />

      {/* Orders List */}
      <div className="space-y-4">
        {pagedOrders.map((order) => (
          <OrderCard
            key={order.id}
            order={order}
            isSelected={selectedOrders.includes(order.id)}
            onSelect={(orderId) =>
              setSelectedOrders((prev) =>
                prev.includes(orderId)
                  ? prev.filter((id) => id !== orderId)
                  : [...prev, orderId],
              )
            }
            onView={(order) => {
              setSelectedOrder(order);
              setIsViewDialogOpen(true);
            }}
            onMarkAsPickedUp={(orderId) =>
              setOrders(markAsPickedUp(orders, orderId))
            }
            onMarkAsReady={(orderId) => setOrders(markAsReady(orders, orderId))}
            onCancelOrder={(orderId) => setOrders(cancelOrder(orders, orderId))}
            onPrintOrder={(order) => printOrder(order)}
          />
        ))}
      </div>

      {/* Order Details Dialog */}
      <OrderDetailsDialog
        order={selectedOrder}
        isOpen={isViewDialogOpen}
        onClose={() => setIsViewDialogOpen(false)}
        onMarkAsPickedUp={(orderId) => {
          setOrders(markAsPickedUp(orders, orderId));
          setIsViewDialogOpen(false);
        }}
        onMarkAsReady={(orderId) => {
          setOrders(markAsReady(orders, orderId));
          setIsViewDialogOpen(false);
        }}
      />
    </div>
  );
}
