import { Vendor } from "../api/vendors.types";

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 1,
    name: "Green Valley Bakery",
    type: "Vendor",
    category: "Bakery",
    contact: "Jane Cooper",
    email: "manager@greenvalley.com",
    phone: "(555) 111-2222",
    address: "123 Valley Road",
    listings: 12,
    revenue: "$842.50",
    rating: 4.8,
    status: "Active",
  },
  {
    id: 2,
    name: "City Cafe",
    type: "Vendor",
    category: "Cafe",
    contact: "Tom Harris",
    email: "contact@citycafe.com",
    phone: "(555) 222-3333",
    address: "456 Main Street",
    listings: 8,
    revenue: "$625.40",
    rating: 4.6,
    status: "Active",
  },
  {
    id: 3,
    name: "Fresh Market",
    type: "Vendor",
    category: "Grocery",
    contact: "Sarah Miller",
    email: "info@freshmarket.com",
    phone: "(555) 333-4444",
    address: "789 Market Ave",
    listings: 15,
    revenue: "$1,124.80",
    rating: 4.9,
    status: "Active",
  },
  {
    id: 4,
    name: "Downtown Deli",
    type: "Vendor",
    category: "Restaurant",
    contact: "Mike Johnson",
    email: "owner@downtowndeli.com",
    phone: "(555) 444-5555",
    address: "321 Downtown Blvd",
    listings: 10,
    revenue: "$758.20",
    rating: 4.7,
    status: "Active",
  },
  {
    id: 5,
    name: "Community Food Bank",
    type: "NGO Partner",
    category: "Non-Profit",
    contact: "Emily Davis",
    email: "info@foodbank.org",
    phone: "(555) 555-6666",
    address: "654 Hope Avenue",
    listings: 0,
    revenue: "$0.00",
    rating: 5.0,
    status: "Active",
  },
  {
    id: 6,
    name: "Organic Bistro",
    type: "Vendor",
    category: "Restaurant",
    contact: "Robert Lee",
    email: "hello@organicbistro.com",
    phone: "(555) 666-7777",
    address: "987 Organic Way",
    listings: 11,
    revenue: "$892.60",
    rating: 4.5,
    status: "Active",
  },
  {
    id: 7,
    name: "Sweet Treats",
    type: "Vendor",
    category: "Bakery",
    contact: "Linda White",
    email: "sweet@treats.com",
    phone: "(555) 777-8888",
    address: "258 Sweet Lane",
    listings: 9,
    revenue: "$698.30",
    rating: 4.8,
    status: "Active",
  },
  {
    id: 8,
    name: "Hope Shelter",
    type: "NGO Partner",
    category: "Non-Profit",
    contact: "James Brown",
    email: "contact@hopeshelter.org",
    phone: "(555) 888-9999",
    address: "147 Shelter Street",
    listings: 0,
    revenue: "$0.00",
    rating: 5.0,
    status: "Active",
  },
];

export const CATEGORIES = [
  "Bakery",
  "Restaurant",
  "Cafe",
  "Grocery",
  "Non-Profit",
];
export const VENDOR_TYPES = ["Vendor", "NGO Partner"];
export const STATUSES = ["Active", "Inactive"];
